; Inno Setup Script for Screen Health Guardian
; Generates a professional Windows installer.

[Setup]
; App Information
AppName=Screen Health Guardian
AppVersion=2.1.1
AppPublisher=AnaCataVC
AppCopyright=Copyright (C) 2026
AppSupportURL=https://github.com/AnaCataVC/screen-health-guardian
AppUpdatesURL=https://github.com/AnaCataVC/screen-health-guardian/releases

; Installer Settings
DefaultDirName={autopf}\Screen Health Guardian
DefaultGroupName=Screen Health Guardian
AllowNoIcons=yes
SetupIconFile=icon.ico
OutputDir=releases
OutputBaseFilename=ScreenHealthGuardian-Setup
Compression=lzma2/normal
SolidCompression=no
PrivilegesRequired=lowest
ArchitecturesInstallIn64BitMode=x64

; Uninstaller Settings
UninstallDisplayIcon={app}\ScreenHealthGuardian.exe
UninstallDisplayName=Screen Health Guardian

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"

[CustomMessages]
english.StartupTask=Start Screen Health Guardian automatically when Windows starts
english.StartupGroup=System Startup:
spanish.StartupTask=Iniciar Screen Health Guardian automáticamente al encender Windows
spanish.StartupGroup=Inicio del Sistema:

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "startupicon"; Description: "{cm:StartupTask}"; GroupDescription: "{cm:StartupGroup}"

[Files]
; Copy standalone executable and bundle files generated by dotnet publish
Source: "releases\win-x64\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
; Start Menu
Name: "{autoprograms}\Screen Health Guardian"; Filename: "{app}\ScreenHealthGuardian.exe"
; Desktop
Name: "{autodesktop}\Screen Health Guardian"; Filename: "{app}\ScreenHealthGuardian.exe"; Tasks: desktopicon
; Startup folder
Name: "{autostartup}\Screen Health Guardian"; Filename: "{app}\ScreenHealthGuardian.exe"; Tasks: startupicon

[Run]
; Option to launch the app immediately after installation
Filename: "{app}\ScreenHealthGuardian.exe"; Description: "{cm:LaunchProgram,Screen Health Guardian}"; Flags: nowait postinstall skipifsilent

[UninstallRun]
; Kill the application if it's running so the files can be deleted
Filename: "{cmd}"; Parameters: "/C taskkill /IM ScreenHealthGuardian.exe /F /T"; Flags: runhidden; RunOnceId: "KillApp"

[UninstallDelete]
; Clean up appdata folder on uninstall
Type: filesandordirs; Name: "{userappdata}\ScreenHealthGuardian"

[Registry]
; Remove the auto-start registry key
Root: HKCU; Subkey: "Software\Microsoft\Windows\CurrentVersion\Run"; ValueType: string; ValueName: "ScreenHealthGuardian"; Flags: uninsdeletevalue
; Save the installation language
Root: HKCU; Subkey: "Software\ScreenHealthGuardian"; ValueType: string; ValueName: "InstallLanguage"; ValueData: "{language}"; Flags: uninsdeletevalue
