; Inno Setup Script for Work Health Timer
; Generates a professional Windows installer.

[Setup]
; App Information
AppName=Work Health Timer
AppVersion=1.0.0
AppPublisher=AnaCataVC
AppCopyright=Copyright (C) 2026
AppSupportURL=https://github.com/AnaCataVC/work-health-timer
AppUpdatesURL=https://github.com/AnaCataVC/work-health-timer/releases

; Installer Settings
DefaultDirName={autopf}\Work Health Timer
DefaultGroupName=Work Health Timer
AllowNoIcons=yes
SetupIconFile=icon.ico
OutputDir=dist
OutputBaseFilename=WorkHealthTimer-Setup
Compression=lzma2/normal
SolidCompression=no
PrivilegesRequired=lowest
ArchitecturesInstallIn64BitMode=x64

; Uninstaller Settings
UninstallDisplayIcon={app}\WorkHealthTimer.exe
UninstallDisplayName=Work Health Timer

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"

[CustomMessages]
english.StartupTask=Start Work Health Timer automatically when Windows starts
english.StartupGroup=System Startup:
spanish.StartupTask=Iniciar Work Health Timer automáticamente al encender Windows
spanish.StartupGroup=Inicio del Sistema:

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "startupicon"; Description: "{cm:StartupTask}"; GroupDescription: "{cm:StartupGroup}"

[Files]
; Copy all files generated by PyInstaller --onedir
Source: "dist\WorkHealthTimer\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
; Start Menu
Name: "{autoprograms}\Work Health Timer"; Filename: "{app}\WorkHealthTimer.exe"
; Desktop
Name: "{autodesktop}\Work Health Timer"; Filename: "{app}\WorkHealthTimer.exe"; Tasks: desktopicon
; Startup folder
Name: "{autostartup}\Work Health Timer"; Filename: "{app}\WorkHealthTimer.exe"; Tasks: startupicon

[Run]
; Option to launch the app immediately after installation
Filename: "{app}\WorkHealthTimer.exe"; Description: "{cm:LaunchProgram,Work Health Timer}"; Flags: nowait postinstall skipifsilent

[UninstallRun]
; Kill the application if it's running so the files can be deleted
Filename: "{cmd}"; Parameters: "/C taskkill /IM WorkHealthTimer.exe /F /T"; Flags: runhidden; RunOnceId: "KillApp"

[UninstallDelete]
; Clean up appdata folder on uninstall
Type: filesandordirs; Name: "{userappdata}\WorkHealthTimer"

[Registry]
; Remove the auto-start registry key
Root: HKCU; Subkey: "Software\Microsoft\Windows\CurrentVersion\Run"; ValueType: string; ValueName: "WorkHealthTimer"; Flags: uninsdeletevalue
; Save the installation language
Root: HKCU; Subkey: "Software\WorkHealthTimer"; ValueType: string; ValueName: "InstallLanguage"; ValueData: "{language}"; Flags: uninsdeletevalue
